name: BuildAndPublish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test_pms:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
      
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./ProductManagementSystem/pms_api
      
      - name: Build
        run: dotnet build
        working-directory: ./ProductManagementSystem/pms_api
        
      - name: Test
        run: dotnet test
        working-directory: ./ProductManagementSystem/pms_api
        
  build_frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
        working-directory: ./Frontend
      
      - name: Install Angular
        run: npm install -g @angular/cli
        
      - name: Build
        run: ng build
        working-directory: ./Frontend
